[package]
name = "exchange_status_scrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.18.1"
reqwest = "0.11.22"
colorful = "0.2.2"
